dist: xenial
arch:
   #- amd64
    - ppc64le
language: python
python:
   # - 2.7
   # - 3.6
   # - 3.7
    - 3.8
before_install:
    - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
    - pip install imutils openblas
     -pip install --upgrade pip setuptools wheel
    - pip install scipy
install:
    - pip install Cython
    - pip install pillow
    - pip install matplotlib
    - pip install shapely
    - pip install scikit-image
    - pip install coverage
    - pip install coveralls
    - pip install codecov
    - pip install codacy-coverage

services:
  - xvfb
script:
  coverage run --source=dicompylercore setup.py test
after_success:
  - coveralls
  - codecov
  - python-codacy-coverage
